<!DOCTYPE html>

<html lang="ja">
<!-- --------------------------------------
head
--------------------------------------- -->
<head>
<meta content="text/html" charset="utf-8" http-equiv="Content-Type" />

<!-- 基準URI -->
<base href="file:///G:/共有ドライブ/098-all-employees/tips/HTML_TIPS/">

<!-- スタイルシート -->
<link rel="stylesheet" href="_Assets/Sytle001.css" type="text/css">

<!-- スクリプト -->
<!-- タイトル表示 -->
<script src="_Assets/MakeTitle.js" type="text/javascript"></script>
<!-- 目次表示 -->
<script src="_Assets/MakeToc.js" type="text/javascript"></script>



</head>

<!-- --------------------------------------
body
--------------------------------------- -->
<body>
<!-- ページタイトル(ページ内表示) -->
<span id="title"></span>

<!-- 出典・関連ページ -->
<h5>出典 :</h5>
<a href="https://qiita.com/eijenson/items/7e9e112e69b37f72353c">try-catch-finally句内のreturnについて - Qiita</a>

<h5>関連 :</h5>
<a href="TIPS/C・C++/[C++]例外処理.html">[C++]例外処理</a>

<!-- 目次 -->
<h5>目次 :</h5>
<div id="toc"></div>

<hr>

<!-- 本文ここから -->


<h2>try - catch - finally 句</h2>
例外処理に伴い、例外の発生有無によらない共通の最終処理(ファイルのクローズ、セマフォの開放など)を行わせたい場合は、<br>
<b>「共通の最終処理」を finally 節に記述する</b>。この最終処理は try 節、または catch 節を抜ける直前に実行される。<br>
例外処理に関しては <a href="TIPS/C・C++/[C++]例外処理.html">ここ</a> を参照のこと。
(C++には finally 句が存在しないが、try - catch による例外処理の文法はC#とC++でほぼ共通である。)

<h2>基本形</h2>
関数 DoSomething() で発生した例外を try 節で捕捉する場合の例。<br>
DoSomething() 内で例外が発生しなかった(正常終了した)場合は、try 節中の以降の処理が実行され、finally 節が実行される。<br>
例外が発生した場合は try 節中の以降の処理はスキップされ、catch 節が実行された後 finally 節が実行される。<br>
すなわち、いずれの場合においても finally 節は実行される。<br>
<img src="_Img/MSVS_DotNet_CSharp/CS_TryCatchFinally/01.png"><br>

<h2>try / catch 節に return を含む場合</h2>
try 節、または catch 節に return を含む場合、<b>finally 節は return 文の直前に実行される</b>。<br>
このため、try / catch 節に return を含む場合、finally 節に return を記述すると、try / catch 節の return は到達できないコードとなる。<br>
これにより例外を握りつぶす可能性があるため、注意が必要。<br>
<img src="_Img/MSVS_DotNet_CSharp/CS_TryCatchFinally/02.png"><br>

</body>
</html>
